// Package ast contains the AST generated by the parser.
// Based on: https://github.com/parcel-bundler/lightningcss/blob/2983614/node/ast.d.ts#L4
package ast

import "strings"

type Visitor interface {
	VisitStylesheet(*Stylesheet)
}

type Node interface {
	String() string
	Visit(Visitor)
}

var (
	_ Node = &Stylesheet{}
)

type Stylesheet struct {
	Rules []Rule
}

func (s *Stylesheet) String() string {
	sb := new(strings.Builder)
	// for _, d := range s.Body {
	// 	sb.WriteString(d.String())
	// }
	return sb.String()
}

func (s *Stylesheet) Visit(v Visitor) {
	v.VisitStylesheet(s)
}

type Rule interface {
	Node
	rule()
}
